version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION: $STRING_SESSION
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      PING_IMG_URL: $PING_IMG_URL
      START_IMG_URL: $START_IMG_URL
      SUPPORT_CHANNEL: $SUPPORT_CHANNEL
      SUPPORT_GROUP: $SUPPORT_GROUP
      DURATION_LIMIT_MIN: $DURATION_LIMIT_MIN
      AUTO_DOWNLOADS_CLEAR: $AUTO_DOWNLOADS_CLEAR
      SPOTIFY_CLIENT_SECRET: $SPOTIFY_CLIENT_SECRET
      SPOTIFY_CLIENT_ID: SPOTIFY_CLIENT_ID
      STRING_SESSION2: $STRING_SESSION2
      
